### ISSUE TITLE
publish update

### ISSUE THREAD

**Issue by juliocbcotta** [facundomedica/fast_qr_reader_view#61]
It looks like the current published version at pub.dev still does not have the AndroidX migration.
Please, publish an update.

**Comment by idofilus** [comment]
Meanwhile you can do:

```
  fast_qr_reader_view:
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git
      ref: 05d629020b19b426c5d8f20a88d5a810ff304d7b
```
